version: "3.8"

services:
  db:
    image: postgres:alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laravel
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - db
      - minio
    ports:
      - "9000:9000"
    links:
      - minio

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9002:9002"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./docker/minio/data:/data
    command: server /data --address ":9002" --console-address ":9001"